### ISSUE TITLE
Config doesn't get loaded after Heroku-deployment

### ISSUE THREAD

**Issue by epaminond** [botpress/botpress-messenger#38]
After deploying to heroku, messenger configuration page remains empty when opened (no fields/buttons), and several requests fail with 404-error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
createError.js:15 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
/api/botpress-messenger/config Failed to load resource: the server responded with a status of 404 (Not Found)
createError.js:15 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
/api/botpress-messenger/users Failed to load resource: the server responded with a status of 404 (Not Found)
web.bundle.js:26582 Uncaught (in promise) Error: Request failed with status code 404
    at createError (web.bundle.js:26582)
    at settle (web.bundle.js:26554)
    at XMLHttpRequest.handleLoad (web.bundle.js:26429)
custom-theme.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by slvnperron** [comment]
Hi Alex, can you confirm you are using Postgres on Heroku? 

https://docs.botpress.io/fundamentals/database.html#heroku

**Comment by epaminond** [comment]
@slvnperron , yes, I'm using postgres there.

**Comment by epaminond** [comment]
I tried it several times. And initially it worked fine for a few hours before issue occurred. But now I get it for newly created project either.

**Comment by slvnperron** [comment]
Weird, can you check your heroku logs and see if there's any error on this side?

**Comment by epaminond** [comment]
I can only see 404-responses there:
```
2017-06-05T10:35:51.513078+00:00 heroku[router]: at=info method=GET path="/js/modules/web.bundle.js.map" host=siriusai-beautybot.herokuapp.com request_id=c61e2875-8b5a-4ab7-9611-ae001797b8fc fwd="178.95.59.179" dyno=web.1 connect=4ms service=8ms status=404 bytes=411 protocol=https
2017-06-05T10:35:51.508156+00:00 heroku[router]: at=info method=GET path="/api/botpress-messenger/homepage" host=siriusai-beautybot.herokuapp.com request_id=30ae23bf-3791-4022-bb59-7c3844b98cf7 fwd="178.95.59.179" dyno=web.1 connect=6ms service=17ms status=404 bytes=414 protocol=https
2017-06-05T10:35:51.501034+00:00 heroku[router]: at=info method=GET path="/api/botpress-messenger/config" host=siriusai-beautybot.herokuapp.com request_id=66ab849f-4d2c-48d2-8736-af544de330d6 fwd="178.95.59.179" dyno=web.1 connect=6ms service=13ms status=404 bytes=412 protocol=https
2017-06-05T10:35:51.511163+00:00 heroku[router]: at=info method=GET path="/api/botpress-messenger/users" host=siriusai-beautybot.herokuapp.com request_id=5cde416f-a28c-4e1d-911c-8822c5a0e461 fwd="178.95.59.179" dyno=web.1 connect=5ms service=12ms status=404 bytes=411 protocol=https
```

**Comment by slvnperron** [comment]
Which version of botpress-messenger do you have installed (you can see that in the bot boot logs)? I also assume that botpress-messenger is in your package.json's dependencies

**Comment by epaminond** [comment]
botpress-messenger is locked to 2.1.1 via package-lock.json
Here are sources: https://github.com/epaminond/beautybot

**Comment by slvnperron** [comment]
@epaminond Error replicated, investigating now

**Comment by slvnperron** [comment]
@epaminond Seems like it can't connect to your DB, can you confirm this in your logs (upper right menu). How are you setting postgres' settings on heroku?

**Comment by epaminond** [comment]
Logs show these errors:
```
Jun 05 13:52:19error: Unhandled Rejection in Promise: Promise { _bitField: 18087936, _fulfillmentHandler0: { Error: connect ECONNREFUSED 127.0.0.1:5432 at Object.exports._errnoException (util.js:1026:11) at exports._exceptionWithHostPort (util.js:1049:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14) code: 'ECONNREFUSED', errno: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 5432 }, _rejectionHandler0: undefined, _promise0: undefined, _receiver0: undefined } Reason:
Jun 05 13:52:19info: Bot launched. Visit: http://localhost:32612
Jun 05 13:52:19error: Unhandled Rejection in Promise: Promise { _bitField: 18087936, _fulfillmentHandler0: { Error: connect ECONNREFUSED 127.0.0.1:5432 at Object.exports._errnoException (util.js:1026:11) at exports._exceptionWithHostPort (util.js:1049:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14) code: 'ECONNREFUSED', errno: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 5432 }, _rejectionHandler0: undefined, _promise0: undefined, _receiver0: undefined } Reason:
```

To set up DB, I've set these env-variables:  DATABASE, DATABASE_URL, PG_DB, PG_HOST, PG_PASSWORD, PG_PORT, PG_USER.

**Comment by slvnperron** [comment]
The problem is that you're not looking into the ENV variables anymore because you load your postgres.json thing.

Here's what I did:

```js
const defaultPostgresSettings = {
  enabled: true,
  connection: process.env.PG_URL || process.env.DATABASE_URL || null
}

const postgres = defaultPostgresSettings
```

DATABASE_URL is set by default by heroku

**Comment by epaminond** [comment]
Oh it seems i accidentally let postgres.json get into repo. Thanks for quick response! :)

**Comment by epaminond** [comment]
@slvnperron , I've fixed that issue, but got another one. Logs show something like this:

```
Jun 05 17:32:21error: Unhandled Rejection in Promise: Promise { _bitField: 18087936, _fulfillmentHandler0: TypeError: Cannot read property 'sendText' of undefined at bp.hear (/app/dialogues/greetings.js:3:17) at /app/node_modules/botpress/lib/webpack:/src/listeners.js:33:9 at exec (/app/node_modules/mware/index.js:50:23) at Function.run
Jun 05 17:31:18info: Bot launched. Visit: http://localhost:35921
Jun 05 17:31:17info: Loaded 1 modules
Jun 05 17:31:17info: Loaded botpress-messenger, version https://registry.npmjs.org/botpress-messenger/-/botpress-messenger-2.1.1.tgz
Jun 05 17:31:17warn: Error during module initialization:
Jun 05 17:31:17info: Starting botpress version 0.2.4
Jun 05 17:31:17info: Creating data directory: /app/modules_config
Jun 05 17:31:17info: Creating data directory: /app/data
```

On middleware tab locally I have botpress-messenger, but it's not there in deployed app.

**Comment by slvnperron** [comment]
@epaminond Found the issue, will push a fix now. Please try again in 10m

**Comment by slvnperron** [comment]
@epaminond You'll need to upgrade to messenger@2.1.2 -- Let me know if that worked. Thanks

**Comment by epaminond** [comment]
@slvnperron , this helped, thanks!
